### ISSUE TITLE
Email Fetch Error

### ISSUE THREAD

**Issue by Imagine-YT** [Junaid433/CS-Info-Grabber#3]
Email Is Not Being Able To Be Parsed Properly And Is Always NONE.

**Comment by Junaid433** [comment]
@Imagine-YT getCustomerEmail function is working properly. Make sure the checkout link you input has a email added.

![Screenshot (398)](https://user-images.githubusercontent.com/91566370/235640888-2d79f86e-0d89-49ca-b149-22125feef662.png)
